#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED

#define DISTRHO_PLUGIN_BRAND    "mxmilkiib"
#define DISTRHO_PLUGIN_NAME     "Halftime"
#define DISTRHO_PLUGIN_URI      "https://github.com/milkii/halftime-lv2"
#define DISTRHO_PLUGIN_CLAP_ID  "com.mxmilkiib.halftime"

#define DISTRHO_PLUGIN_BRAND_ID  Mlki
#define DISTRHO_PLUGIN_UNIQUE_ID dHtm

#define DISTRHO_PLUGIN_HAS_UI          1
#define DISTRHO_PLUGIN_IS_RT_SAFE      1
#define DISTRHO_PLUGIN_NUM_INPUTS      2
#define DISTRHO_PLUGIN_NUM_OUTPUTS     2
#define DISTRHO_PLUGIN_WANT_TIMEPOS    1
#define DISTRHO_PLUGIN_WANT_LATENCY    1
#define DISTRHO_PLUGIN_WANT_PROGRAMS   1
#define DISTRHO_PLUGIN_WANT_STATE      0
#define DISTRHO_UI_USE_NANOVG          1
#define DISTRHO_UI_FILE_BROWSER        0
#define DISTRHO_UI_USER_RESIZABLE      1
#define DISTRHO_UI_DEFAULT_WIDTH       1400
#define DISTRHO_UI_DEFAULT_HEIGHT      680

#endif // DISTRHO_PLUGIN_INFO_H_INCLUDED
